export const tracks = [
  {
    id: "0",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    title: "Track 1",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "1",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    title: "Track 2",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "2",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    title: "Track 3",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "3",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    title: "Track 4",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "4",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    title: "Track 5",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "5",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    title: "Track 6",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "6",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    title: "Track 7",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "7",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    title: "Track 8",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "8",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    title: "Track 9",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "9",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    title: "Track 10",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "10",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    title: "Track 11",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "11",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    title: "Track 12",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "12",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    title: "Track 13",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "13",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    title: "Track 14",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "14",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    title: "Track 15",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
  {
    id: "15",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    title: "Track 16",
    artist: "Some Artist",
    artwork: "https://picsum.photos/400",
  },
];
