export const tracks = [
  {
    id: "0",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    title: "SoundHelix Song 1",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/203/400",
  },
  {
    id: "1",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    title: "SoundHelix Song 2",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/202/400",
  },
  {
    id: "2",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    title: "SoundHelix Song 3",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/1000/400",
  },
  {
    id: "3",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    title: "SoundHelix Song 4",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/732/400",
  },
  {
    id: "4",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    title: "SoundHelix Song 5",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/444/400",
  },
  {
    id: "5",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    title: "SoundHelix Song 6",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/555/400",
  },
  {
    id: "6",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    title: "SoundHelix Song 7",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/778/400",
  },
  {
    id: "7",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    title: "SoundHelix Song 8",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/888/400",
  },
  {
    id: "8",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    title: "SoundHelix Song 9",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/999/400",
  },
  {
    id: "9",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    title: "SoundHelix Song 10",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/1021/400",
  },
  {
    id: "10",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    title: "SoundHelix Song 11",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/14/400",
  },
  {
    id: "11",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    title: "SoundHelix Song 12",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/92/400",
  },
  {
    id: "12",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    title: "SoundHelix Song 13",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/356/400",
  },
  {
    id: "13",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    title: "SoundHelix Song 14",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/983/400",
  },
  {
    id: "14",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    title: "SoundHelix Song 15",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/82/400",
  },
  {
    id: "15",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    title: "SoundHelix Song 16",
    artist: "T. Schürger",
    artwork: "https://picsum.photos/id/936/400",
  },
];
